// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/engine_builder.proto

package org.mozc.android.inputmethod.japanese.protobuf;

public final class ProtoEngineBuilder {
  private ProtoEngineBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EngineReloadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mozc.EngineReloadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return Whether the filePath field is set.
     */
    boolean hasFilePath();
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The filePath.
     */
    java.lang.String getFilePath();
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return Whether the magicNumber field is set.
     */
    boolean hasMagicNumber();
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The magicNumber.
     */
    java.lang.String getMagicNumber();
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The bytes for magicNumber.
     */
    com.google.protobuf.ByteString
        getMagicNumberBytes();

    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    boolean hasPriority();
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return The priority.
     */
    int getPriority();
  }
  /**
   * Protobuf type {@code mozc.EngineReloadRequest}
   */
  public static final class EngineReloadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mozc.EngineReloadRequest)
      EngineReloadRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EngineReloadRequest.newBuilder() to construct.
    private EngineReloadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EngineReloadRequest() {
      filePath_ = "";
      magicNumber_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EngineReloadRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.class, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FILE_PATH_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filePath_ = "";
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return Whether the filePath field is set.
     */
    @java.lang.Override
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filePath_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Path to the data file to be loaded in a new engine.
     * </pre>
     *
     * <code>required string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAGIC_NUMBER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object magicNumber_ = "";
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return Whether the magicNumber field is set.
     */
    @java.lang.Override
    public boolean hasMagicNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The magicNumber.
     */
    @java.lang.Override
    public java.lang.String getMagicNumber() {
      java.lang.Object ref = magicNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          magicNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Explicitly specifies the magic number to be used for data validation.
     * Since acceptable magic number is embedded in Mozc server, this option is
     * unnecessary for normal cases.  However, this is required for some unit
     * tests as test data has a different magic number.
     * </pre>
     *
     * <code>optional string magic_number = 4;</code>
     * @return The bytes for magicNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMagicNumberBytes() {
      java.lang.Object ref = magicNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        magicNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_ = 0;
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return Whether the priority field is set.
     */
    @java.lang.Override
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Priority of the request (smaller is more prioritized).
     * The decoder keeps all the requests, and uses the most prioritized one.
     * For the same priority request, later one overrides existing one.
     * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filePath_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, magicNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(5, priority_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filePath_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, magicNumber_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest)) {
        return super.equals(obj);
      }
      org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest other = (org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest) obj;

      if (hasFilePath() != other.hasFilePath()) return false;
      if (hasFilePath()) {
        if (!getFilePath()
            .equals(other.getFilePath())) return false;
      }
      if (hasMagicNumber() != other.hasMagicNumber()) return false;
      if (hasMagicNumber()) {
        if (!getMagicNumber()
            .equals(other.getMagicNumber())) return false;
      }
      if (hasPriority() != other.hasPriority()) return false;
      if (hasPriority()) {
        if (getPriority()
            != other.getPriority()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilePath()) {
        hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getFilePath().hashCode();
      }
      if (hasMagicNumber()) {
        hash = (37 * hash) + MAGIC_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getMagicNumber().hashCode();
      }
      if (hasPriority()) {
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getPriority();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mozc.EngineReloadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mozc.EngineReloadRequest)
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.class, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder.class);
      }

      // Construct using org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        filePath_ = "";
        magicNumber_ = "";
        priority_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadRequest_descriptor;
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getDefaultInstanceForType() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest build() {
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest buildPartial() {
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest result = new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.filePath_ = filePath_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.magicNumber_ = magicNumber_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.priority_ = priority_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest) {
          return mergeFrom((org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest other) {
        if (other == org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          filePath_ = other.filePath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasMagicNumber()) {
          magicNumber_ = other.magicNumber_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFilePath()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                filePath_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 34: {
                magicNumber_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 34
              case 40: {
                priority_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object filePath_ = "";
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return Whether the filePath field is set.
       */
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return The filePath.
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filePath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return The bytes for filePath.
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        filePath_ = getDefaultInstance().getFilePath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the data file to be loaded in a new engine.
       * </pre>
       *
       * <code>required string file_path = 2;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        filePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object magicNumber_ = "";
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return Whether the magicNumber field is set.
       */
      public boolean hasMagicNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return The magicNumber.
       */
      public java.lang.String getMagicNumber() {
        java.lang.Object ref = magicNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            magicNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return The bytes for magicNumber.
       */
      public com.google.protobuf.ByteString
          getMagicNumberBytes() {
        java.lang.Object ref = magicNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          magicNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @param value The magicNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        magicNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagicNumber() {
        magicNumber_ = getDefaultInstance().getMagicNumber();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Explicitly specifies the magic number to be used for data validation.
       * Since acceptable magic number is embedded in Mozc server, this option is
       * unnecessary for normal cases.  However, this is required for some unit
       * tests as test data has a different magic number.
       * </pre>
       *
       * <code>optional string magic_number = 4;</code>
       * @param value The bytes for magicNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        magicNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return Whether the priority field is set.
       */
      @java.lang.Override
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return The priority.
       */
      @java.lang.Override
      public int getPriority() {
        return priority_;
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Priority of the request (smaller is more prioritized).
       * The decoder keeps all the requests, and uses the most prioritized one.
       * For the same priority request, later one overrides existing one.
       * Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mozc.EngineReloadRequest)
    }

    // @@protoc_insertion_point(class_scope:mozc.EngineReloadRequest)
    private static final org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest();
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EngineReloadRequest>
        PARSER = new com.google.protobuf.AbstractParser<EngineReloadRequest>() {
      @java.lang.Override
      public EngineReloadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngineReloadRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngineReloadRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EngineReloadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mozc.EngineReloadResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return The status.
     */
    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus();

    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return The request.
     */
    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest();
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code mozc.EngineReloadResponse}
   */
  public static final class EngineReloadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mozc.EngineReloadResponse)
      EngineReloadResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EngineReloadResponse.newBuilder() to construct.
    private EngineReloadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EngineReloadResponse() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EngineReloadResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.class, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code mozc.EngineReloadResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Reload command is accepted.
       * </pre>
       *
       * <code>ACCEPTED = 0;</code>
       */
      ACCEPTED(0),
      /**
       * <pre>
       * New data is verified and ready.
       * </pre>
       *
       * <code>RELOAD_READY = 1;</code>
       */
      RELOAD_READY(1),
      /**
       * <pre>
       * Engine was replaced by a new instance.
       * </pre>
       *
       * <code>RELOADED = 2;</code>
       */
      RELOADED(2),
      /**
       * <pre>
       * Failed to start reload because another reload job is currently running.
       * </pre>
       *
       * <code>ALREADY_RUNNING = 3;</code>
       */
      ALREADY_RUNNING(3),
      /**
       * <pre>
       * Errors in data file.
       * </pre>
       *
       * <code>ENGINE_VERSION_MISMATCH = 4;</code>
       */
      ENGINE_VERSION_MISMATCH(4),
      /**
       * <code>DATA_MISSING = 5;</code>
       */
      DATA_MISSING(5),
      /**
       * <code>DATA_BROKEN = 6;</code>
       */
      DATA_BROKEN(6),
      /**
       * <pre>
       * File doesn't exist or underlying memory mapping failed.
       * </pre>
       *
       * <code>MMAP_FAILURE = 7;</code>
       */
      MMAP_FAILURE(7),
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      UNKNOWN_ERROR(9),
      ;

      /**
       * <pre>
       * Reload command is accepted.
       * </pre>
       *
       * <code>ACCEPTED = 0;</code>
       */
      public static final int ACCEPTED_VALUE = 0;
      /**
       * <pre>
       * New data is verified and ready.
       * </pre>
       *
       * <code>RELOAD_READY = 1;</code>
       */
      public static final int RELOAD_READY_VALUE = 1;
      /**
       * <pre>
       * Engine was replaced by a new instance.
       * </pre>
       *
       * <code>RELOADED = 2;</code>
       */
      public static final int RELOADED_VALUE = 2;
      /**
       * <pre>
       * Failed to start reload because another reload job is currently running.
       * </pre>
       *
       * <code>ALREADY_RUNNING = 3;</code>
       */
      public static final int ALREADY_RUNNING_VALUE = 3;
      /**
       * <pre>
       * Errors in data file.
       * </pre>
       *
       * <code>ENGINE_VERSION_MISMATCH = 4;</code>
       */
      public static final int ENGINE_VERSION_MISMATCH_VALUE = 4;
      /**
       * <code>DATA_MISSING = 5;</code>
       */
      public static final int DATA_MISSING_VALUE = 5;
      /**
       * <code>DATA_BROKEN = 6;</code>
       */
      public static final int DATA_BROKEN_VALUE = 6;
      /**
       * <pre>
       * File doesn't exist or underlying memory mapping failed.
       * </pre>
       *
       * <code>MMAP_FAILURE = 7;</code>
       */
      public static final int MMAP_FAILURE_VALUE = 7;
      /**
       * <code>UNKNOWN_ERROR = 9;</code>
       */
      public static final int UNKNOWN_ERROR_VALUE = 9;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return ACCEPTED;
          case 1: return RELOAD_READY;
          case 2: return RELOADED;
          case 3: return ALREADY_RUNNING;
          case 4: return ENGINE_VERSION_MISMATCH;
          case 5: return DATA_MISSING;
          case 6: return DATA_BROKEN;
          case 7: return MMAP_FAILURE;
          case 9: return UNKNOWN_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mozc.EngineReloadResponse.Status)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus() {
      org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status result = org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.forNumber(status_);
      return result == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.ACCEPTED : result;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest request_;
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest() {
      return request_ == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance() : request_;
    }
    /**
     * <pre>
     * The original request is copied in response for convenience (the reload
     * command runs asynchronously but client doesn't need to keep the original
     * request).
     * </pre>
     *
     * <code>optional .mozc.EngineReloadRequest request = 2;</code>
     */
    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance() : request_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getRequest());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse)) {
        return super.equals(obj);
      }
      org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse other = (org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mozc.EngineReloadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mozc.EngineReloadResponse)
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.class, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Builder.class);
      }

      // Construct using org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.internal_static_mozc_EngineReloadResponse_descriptor;
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse getDefaultInstanceForType() {
        return org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse build() {
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse buildPartial() {
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse result = new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.request_ = requestBuilder_ == null
              ? request_
              : requestBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse) {
          return mergeFrom((org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse other) {
        if (other == org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status tmpValue =
                    org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  status_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status getStatus() {
        org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status result = org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.forNumber(status_);
        return result == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status.ACCEPTED : result;
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .mozc.EngineReloadResponse.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder> requestBuilder_;
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       * @return The request.
       */
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder setRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder setRequest(
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder mergeRequest(org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            request_ != null &&
            request_ != org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance()) {
            getRequestBuilder().mergeFrom(value);
          } else {
            request_ = value;
          }
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <pre>
       * The original request is copied in response for convenience (the reload
       * command runs asynchronously but client doesn't need to keep the original
       * request).
       * </pre>
       *
       * <code>optional .mozc.EngineReloadRequest request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequest.Builder, org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mozc.EngineReloadResponse)
    }

    // @@protoc_insertion_point(class_scope:mozc.EngineReloadResponse)
    private static final org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse();
    }

    public static org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EngineReloadResponse>
        PARSER = new com.google.protobuf.AbstractParser<EngineReloadResponse>() {
      @java.lang.Override
      public EngineReloadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngineReloadResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngineReloadResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mozc.android.inputmethod.japanese.protobuf.ProtoEngineBuilder.EngineReloadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mozc_EngineReloadRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mozc_EngineReloadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mozc_EngineReloadResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mozc_EngineReloadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protocol/engine_builder.proto\022\004mozc\"\\\n" +
      "\023EngineReloadRequest\022\021\n\tfile_path\030\002 \002(\t\022" +
      "\024\n\014magic_number\030\004 \001(\t\022\020\n\010priority\030\005 \001(\005J" +
      "\004\010\001\020\002J\004\010\003\020\004\"\271\002\n\024EngineReloadResponse\0221\n\006" +
      "status\030\001 \002(\0162!.mozc.EngineReloadResponse" +
      ".Status\022*\n\007request\030\002 \001(\0132\031.mozc.EngineRe" +
      "loadRequest\"\301\001\n\006Status\022\014\n\010ACCEPTED\020\000\022\020\n\014" +
      "RELOAD_READY\020\001\022\014\n\010RELOADED\020\002\022\023\n\017ALREADY_" +
      "RUNNING\020\003\022\033\n\027ENGINE_VERSION_MISMATCH\020\004\022\020" +
      "\n\014DATA_MISSING\020\005\022\017\n\013DATA_BROKEN\020\006\022\020\n\014MMA" +
      "P_FAILURE\020\007\022\021\n\rUNKNOWN_ERROR\020\t*\017INSTALL_" +
      "FAILUREBD\n.org.mozc.android.inputmethod." +
      "japanese.protobufB\022ProtoEngineBuilder"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mozc_EngineReloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mozc_EngineReloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mozc_EngineReloadRequest_descriptor,
        new java.lang.String[] { "FilePath", "MagicNumber", "Priority", });
    internal_static_mozc_EngineReloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mozc_EngineReloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mozc_EngineReloadResponse_descriptor,
        new java.lang.String[] { "Status", "Request", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
