// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/ipc.proto

package mozc.ipc;

public final class Ipc {
  private Ipc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IPCPathInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mozc.ipc.IPCPathInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * protocol version
     * </pre>
     *
     * <code>optional uint32 protocol_version = 4 [default = 0];</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <pre>
     * protocol version
     * </pre>
     *
     * <code>optional uint32 protocol_version = 4 [default = 0];</code>
     * @return The protocolVersion.
     */
    int getProtocolVersion();

    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return Whether the productVersion field is set.
     */
    boolean hasProductVersion();
    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return The productVersion.
     */
    java.lang.String getProductVersion();
    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return The bytes for productVersion.
     */
    com.google.protobuf.ByteString
        getProductVersionBytes();

    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <pre>
     * process id of the server
     * </pre>
     *
     * <code>optional uint32 process_id = 2 [default = 0];</code>
     * @return Whether the processId field is set.
     */
    boolean hasProcessId();
    /**
     * <pre>
     * process id of the server
     * </pre>
     *
     * <code>optional uint32 process_id = 2 [default = 0];</code>
     * @return The processId.
     */
    int getProcessId();

    /**
     * <pre>
     * thread id of main listener thread
     * Thread id is not available non-windows environment.
     * Even for windows, thread_id is not used
     * </pre>
     *
     * <code>optional uint32 thread_id = 3 [default = 0];</code>
     * @return Whether the threadId field is set.
     */
    boolean hasThreadId();
    /**
     * <pre>
     * thread id of main listener thread
     * Thread id is not available non-windows environment.
     * Even for windows, thread_id is not used
     * </pre>
     *
     * <code>optional uint32 thread_id = 3 [default = 0];</code>
     * @return The threadId.
     */
    int getThreadId();
  }
  /**
   * Protobuf type {@code mozc.ipc.IPCPathInfo}
   */
  public static final class IPCPathInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mozc.ipc.IPCPathInfo)
      IPCPathInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IPCPathInfo.newBuilder() to construct.
    private IPCPathInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IPCPathInfo() {
      productVersion_ = "0.0.0.0";
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IPCPathInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mozc.ipc.Ipc.internal_static_mozc_ipc_IPCPathInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mozc.ipc.Ipc.internal_static_mozc_ipc_IPCPathInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mozc.ipc.Ipc.IPCPathInfo.class, mozc.ipc.Ipc.IPCPathInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 4;
    private int protocolVersion_ = 0;
    /**
     * <pre>
     * protocol version
     * </pre>
     *
     * <code>optional uint32 protocol_version = 4 [default = 0];</code>
     * @return Whether the protocolVersion field is set.
     */
    @java.lang.Override
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * protocol version
     * </pre>
     *
     * <code>optional uint32 protocol_version = 4 [default = 0];</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public int getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int PRODUCT_VERSION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productVersion_ = "0.0.0.0";
    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return Whether the productVersion field is set.
     */
    @java.lang.Override
    public boolean hasProductVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return The productVersion.
     */
    @java.lang.Override
    public java.lang.String getProductVersion() {
      java.lang.Object ref = productVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * product version
     * </pre>
     *
     * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
     * @return The bytes for productVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductVersionBytes() {
      java.lang.Object ref = productVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * path key name
     * </pre>
     *
     * <code>optional string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESS_ID_FIELD_NUMBER = 2;
    private int processId_ = 0;
    /**
     * <pre>
     * process id of the server
     * </pre>
     *
     * <code>optional uint32 process_id = 2 [default = 0];</code>
     * @return Whether the processId field is set.
     */
    @java.lang.Override
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * process id of the server
     * </pre>
     *
     * <code>optional uint32 process_id = 2 [default = 0];</code>
     * @return The processId.
     */
    @java.lang.Override
    public int getProcessId() {
      return processId_;
    }

    public static final int THREAD_ID_FIELD_NUMBER = 3;
    private int threadId_ = 0;
    /**
     * <pre>
     * thread id of main listener thread
     * Thread id is not available non-windows environment.
     * Even for windows, thread_id is not used
     * </pre>
     *
     * <code>optional uint32 thread_id = 3 [default = 0];</code>
     * @return Whether the threadId field is set.
     */
    @java.lang.Override
    public boolean hasThreadId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * thread id of main listener thread
     * Thread id is not available non-windows environment.
     * Even for windows, thread_id is not used
     * </pre>
     *
     * <code>optional uint32 thread_id = 3 [default = 0];</code>
     * @return The threadId.
     */
    @java.lang.Override
    public int getThreadId() {
      return threadId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(2, processId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(3, threadId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(4, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, processId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, threadId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mozc.ipc.Ipc.IPCPathInfo)) {
        return super.equals(obj);
      }
      mozc.ipc.Ipc.IPCPathInfo other = (mozc.ipc.Ipc.IPCPathInfo) obj;

      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (getProtocolVersion()
            != other.getProtocolVersion()) return false;
      }
      if (hasProductVersion() != other.hasProductVersion()) return false;
      if (hasProductVersion()) {
        if (!getProductVersion()
            .equals(other.getProductVersion())) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasProcessId() != other.hasProcessId()) return false;
      if (hasProcessId()) {
        if (getProcessId()
            != other.getProcessId()) return false;
      }
      if (hasThreadId() != other.hasThreadId()) return false;
      if (hasThreadId()) {
        if (getThreadId()
            != other.getThreadId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion();
      }
      if (hasProductVersion()) {
        hash = (37 * hash) + PRODUCT_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProductVersion().hashCode();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasProcessId()) {
        hash = (37 * hash) + PROCESS_ID_FIELD_NUMBER;
        hash = (53 * hash) + getProcessId();
      }
      if (hasThreadId()) {
        hash = (37 * hash) + THREAD_ID_FIELD_NUMBER;
        hash = (53 * hash) + getThreadId();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mozc.ipc.Ipc.IPCPathInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mozc.ipc.Ipc.IPCPathInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mozc.ipc.IPCPathInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mozc.ipc.IPCPathInfo)
        mozc.ipc.Ipc.IPCPathInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mozc.ipc.Ipc.internal_static_mozc_ipc_IPCPathInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mozc.ipc.Ipc.internal_static_mozc_ipc_IPCPathInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mozc.ipc.Ipc.IPCPathInfo.class, mozc.ipc.Ipc.IPCPathInfo.Builder.class);
      }

      // Construct using mozc.ipc.Ipc.IPCPathInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        protocolVersion_ = 0;
        productVersion_ = "0.0.0.0";
        key_ = "";
        processId_ = 0;
        threadId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mozc.ipc.Ipc.internal_static_mozc_ipc_IPCPathInfo_descriptor;
      }

      @java.lang.Override
      public mozc.ipc.Ipc.IPCPathInfo getDefaultInstanceForType() {
        return mozc.ipc.Ipc.IPCPathInfo.getDefaultInstance();
      }

      @java.lang.Override
      public mozc.ipc.Ipc.IPCPathInfo build() {
        mozc.ipc.Ipc.IPCPathInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mozc.ipc.Ipc.IPCPathInfo buildPartial() {
        mozc.ipc.Ipc.IPCPathInfo result = new mozc.ipc.Ipc.IPCPathInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(mozc.ipc.Ipc.IPCPathInfo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolVersion_ = protocolVersion_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.productVersion_ = productVersion_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.processId_ = processId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.threadId_ = threadId_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mozc.ipc.Ipc.IPCPathInfo) {
          return mergeFrom((mozc.ipc.Ipc.IPCPathInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mozc.ipc.Ipc.IPCPathInfo other) {
        if (other == mozc.ipc.Ipc.IPCPathInfo.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasProductVersion()) {
          productVersion_ = other.productVersion_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasProcessId()) {
          setProcessId(other.getProcessId());
        }
        if (other.hasThreadId()) {
          setThreadId(other.getThreadId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 10
              case 16: {
                processId_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 16
              case 24: {
                threadId_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 24
              case 32: {
                protocolVersion_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 32
              case 42: {
                productVersion_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int protocolVersion_ ;
      /**
       * <pre>
       * protocol version
       * </pre>
       *
       * <code>optional uint32 protocol_version = 4 [default = 0];</code>
       * @return Whether the protocolVersion field is set.
       */
      @java.lang.Override
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * protocol version
       * </pre>
       *
       * <code>optional uint32 protocol_version = 4 [default = 0];</code>
       * @return The protocolVersion.
       */
      @java.lang.Override
      public int getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <pre>
       * protocol version
       * </pre>
       *
       * <code>optional uint32 protocol_version = 4 [default = 0];</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(int value) {
        
        protocolVersion_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocol version
       * </pre>
       *
       * <code>optional uint32 protocol_version = 4 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productVersion_ = "0.0.0.0";
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @return Whether the productVersion field is set.
       */
      public boolean hasProductVersion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @return The productVersion.
       */
      public java.lang.String getProductVersion() {
        java.lang.Object ref = productVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @return The bytes for productVersion.
       */
      public com.google.protobuf.ByteString
          getProductVersionBytes() {
        java.lang.Object ref = productVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @param value The productVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProductVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productVersion_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @return This builder for chaining.
       */
      public Builder clearProductVersion() {
        productVersion_ = getDefaultInstance().getProductVersion();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * product version
       * </pre>
       *
       * <code>optional string product_version = 5 [default = "0.0.0.0"];</code>
       * @param value The bytes for productVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProductVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        productVersion_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * path key name
       * </pre>
       *
       * <code>optional string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int processId_ ;
      /**
       * <pre>
       * process id of the server
       * </pre>
       *
       * <code>optional uint32 process_id = 2 [default = 0];</code>
       * @return Whether the processId field is set.
       */
      @java.lang.Override
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * process id of the server
       * </pre>
       *
       * <code>optional uint32 process_id = 2 [default = 0];</code>
       * @return The processId.
       */
      @java.lang.Override
      public int getProcessId() {
        return processId_;
      }
      /**
       * <pre>
       * process id of the server
       * </pre>
       *
       * <code>optional uint32 process_id = 2 [default = 0];</code>
       * @param value The processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessId(int value) {
        
        processId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * process id of the server
       * </pre>
       *
       * <code>optional uint32 process_id = 2 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        processId_ = 0;
        onChanged();
        return this;
      }

      private int threadId_ ;
      /**
       * <pre>
       * thread id of main listener thread
       * Thread id is not available non-windows environment.
       * Even for windows, thread_id is not used
       * </pre>
       *
       * <code>optional uint32 thread_id = 3 [default = 0];</code>
       * @return Whether the threadId field is set.
       */
      @java.lang.Override
      public boolean hasThreadId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * thread id of main listener thread
       * Thread id is not available non-windows environment.
       * Even for windows, thread_id is not used
       * </pre>
       *
       * <code>optional uint32 thread_id = 3 [default = 0];</code>
       * @return The threadId.
       */
      @java.lang.Override
      public int getThreadId() {
        return threadId_;
      }
      /**
       * <pre>
       * thread id of main listener thread
       * Thread id is not available non-windows environment.
       * Even for windows, thread_id is not used
       * </pre>
       *
       * <code>optional uint32 thread_id = 3 [default = 0];</code>
       * @param value The threadId to set.
       * @return This builder for chaining.
       */
      public Builder setThreadId(int value) {
        
        threadId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * thread id of main listener thread
       * Thread id is not available non-windows environment.
       * Even for windows, thread_id is not used
       * </pre>
       *
       * <code>optional uint32 thread_id = 3 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearThreadId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        threadId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mozc.ipc.IPCPathInfo)
    }

    // @@protoc_insertion_point(class_scope:mozc.ipc.IPCPathInfo)
    private static final mozc.ipc.Ipc.IPCPathInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mozc.ipc.Ipc.IPCPathInfo();
    }

    public static mozc.ipc.Ipc.IPCPathInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IPCPathInfo>
        PARSER = new com.google.protobuf.AbstractParser<IPCPathInfo>() {
      @java.lang.Override
      public IPCPathInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IPCPathInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IPCPathInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mozc.ipc.Ipc.IPCPathInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mozc_ipc_IPCPathInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mozc_ipc_IPCPathInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ripc/ipc.proto\022\010mozc.ipc\"\206\001\n\013IPCPathInf" +
      "o\022\033\n\020protocol_version\030\004 \001(\r:\0010\022 \n\017produc" +
      "t_version\030\005 \001(\t:\0070.0.0.0\022\013\n\003key\030\001 \001(\t\022\025\n" +
      "\nprocess_id\030\002 \001(\r:\0010\022\024\n\tthread_id\030\003 \001(\r:" +
      "\0010"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mozc_ipc_IPCPathInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mozc_ipc_IPCPathInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mozc_ipc_IPCPathInfo_descriptor,
        new java.lang.String[] { "ProtocolVersion", "ProductVersion", "Key", "ProcessId", "ThreadId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
